"""user locale and theme

Revision ID: 197269162e60
Revises: b2f7688db906
Create Date: 2026-07-23 22:53:57.779876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197269162e60'
down_revision: Union[str, Sequence[str], None] = 'b2f7688db906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=5), server_default='uz', nullable=False))
    op.add_column('users', sa.Column('theme', sa.String(length=10), server_default='light', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
