"""exchange settings

Revision ID: 2c167f7f2137
Revises: 7528f8cb3ad8
Create Date: 2026-07-23 22:12:36.738305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c167f7f2137'
down_revision: Union[str, Sequence[str], None] = '7528f8cb3ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_settings',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=10), nullable=False),
    sa.Column('can_receive', sa.Boolean(), nullable=False),
    sa.Column('can_send', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_settings')),
    sa.UniqueConstraint('entity_type', name=op.f('uq_exchange_settings_entity_type'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_settings')
    # ### end Alembic commands ###
