"""outbound messages and telegram binding

Revision ID: 7528f8cb3ad8
Revises: 88f138381971
Create Date: 2026-07-23 21:48:24.246192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7528f8cb3ad8'
down_revision: Union[str, Sequence[str], None] = '88f138381971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_messages',
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_messages'))
    )
    op.create_index('ix_outbound_status', 'outbound_messages', ['status'], unique=False)
    op.add_column('users', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('telegram_link_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_link_code')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_index('ix_outbound_status', table_name='outbound_messages')
    op.drop_table('outbound_messages')
    # ### end Alembic commands ###
