"""outbound html body

Revision ID: b2f7688db906
Revises: 2c167f7f2137
Create Date: 2026-07-23 22:21:03.601499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f7688db906'
down_revision: Union[str, Sequence[str], None] = '2c167f7f2137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_messages', sa.Column('html_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_messages', 'html_body')
    # ### end Alembic commands ###
