"""notifications and comments

Revision ID: cc75b51e87d9
Revises: 8421915b4730
Create Date: 2026-07-23 17:02:29.323500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc75b51e87d9'
down_revision: Union[str, Sequence[str], None] = '8421915b4730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read'], unique=False)
    op.create_table('process_comments',
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_instances.id'], name=op.f('fk_process_comments_process_id_process_instances')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_process_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_comments'))
    )
    op.create_index('ix_process_comments_process', 'process_comments', ['process_id'], unique=False)
    op.drop_constraint(op.f('uq_memos_number'), 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_documents_number'), 'documents', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_documents_number'), 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_memos_number'), 'documents', ['number'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_process_comments_process', table_name='process_comments')
    op.drop_table('process_comments')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
