"""initial schema

Revision ID: e92b456ad3be
Revises: 
Create Date: 2026-07-22 15:14:17.922317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e92b456ad3be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TERMINATED', name='employeestatus'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('external_id', name=op.f('uq_employees_external_id'))
    )
    op.create_table('external_mapping',
    sa.Column('system', sa.Enum('ZUP', 'BUH', 'AD', name='externalsystem'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('internal_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_mapping')),
    sa.UniqueConstraint('system', 'entity_type', 'external_id', name='uq_external_mapping_key')
    )
    op.create_table('integration_outbox',
    sa.Column('target_system', sa.Enum('ZUP', 'BUH', 'AD', name='externalsystem'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACKED', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_outbox')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_integration_outbox_idempotency_key'))
    )
    op.create_table('organizations',
    sa.Column('external_id_buh', sa.UUID(), nullable=True),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('bin', name=op.f('uq_organizations_bin')),
    sa.UniqueConstraint('external_id_buh', name=op.f('uq_organizations_external_id_buh'))
    )
    op.create_table('positions',
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('external_id', name=op.f('uq_positions_external_id'))
    )
    op.create_table('sync_log',
    sa.Column('system', sa.Enum('ZUP', 'BUH', 'AD', name='externalsystem'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='syncdirection'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_log'))
    )
    op.create_table('absences',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('VACATION', 'SICK_LEAVE', 'OTHER', name='absencetype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_absences_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absences'))
    )
    op.create_table('departments',
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name=op.f('fk_departments_parent_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('external_id', name=op.f('uq_departments_external_id'))
    )
    op.create_table('projects',
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('external_id', name=op.f('uq_projects_external_id'))
    )
    op.create_table('substitutions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('substitute_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_substitutions_employee_id_employees')),
    sa.ForeignKeyConstraint(['substitute_id'], ['employees.id'], name=op.f('fk_substitutions_substitute_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substitutions'))
    )
    op.create_table('users',
    sa.Column('ad_object_guid', sa.UUID(), nullable=False),
    sa.Column('ad_sam_account_name', sa.String(length=256), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('ad_object_guid', name=op.f('uq_users_ad_object_guid'))
    )
    op.create_table('employments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employments_department_id_departments')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employments_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_employments_position_id_positions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employments'))
    )
    op.create_table('memos',
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_memos_author_id_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_memos_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memos'))
    )
    op.create_table('process_instances',
    sa.Column('object_type', sa.Enum('MEMO', 'CONTRACT_REQUEST', 'PAYMENT_REQUEST', name='objecttype'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'REJECTED', 'APPROVED', 'PENDING_EXPORT', 'EXPORTED', 'CANCELLED', 'FORCE_CLOSED', name='processstatus'), nullable=False),
    sa.Column('route_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], name=op.f('fk_process_instances_initiator_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_process_instances_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_process_instances_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_instances'))
    )
    op.create_table('project_assignments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_project_assignments_employee_id_employees')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_project_assignments_position_id_positions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_assignments_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_assignments'))
    )
    op.create_table('route_rules',
    sa.Column('object_type', sa.Enum('MEMO', 'CONTRACT_REQUEST', 'PAYMENT_REQUEST', name='objecttype'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('order_in_stage', sa.Integer(), nullable=False),
    sa.Column('resolver_type', sa.Enum('POSITION_IN_ORG', 'POSITION_IN_PROJECT', 'INITIATOR', 'INITIATOR_MANAGER', 'PROJECT_MANAGER', name='resolvertype'), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('stage_type', sa.Enum('SEQUENTIAL', 'PARALLEL_ALL', 'PARALLEL_ANY', 'QUORUM', name='stagetype'), nullable=False),
    sa.Column('quorum_count', sa.Integer(), nullable=True),
    sa.Column('deadline_hours', sa.Integer(), nullable=True),
    sa.Column('mandatory', sa.Enum('REQUIRED', 'OPTIONAL', 'SKIP_IF_NO_ASSIGNEE', name='rulemandatory'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_route_rules_organization_id_organizations')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_route_rules_position_id_positions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_route_rules_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_rules'))
    )
    op.create_index('ix_route_rules_context', 'route_rules', ['object_type', 'organization_id', 'project_id'], unique=False)
    op.create_table('counterparties',
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('external_id', sa.UUID(), nullable=True),
    sa.Column('sync_status', sa.Enum('DRAFT', 'PENDING', 'SYNCED', 'FAILED', 'IMPORTED', name='counterpartysyncstatus'), nullable=False),
    sa.Column('created_from_process_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_from_process_id'], ['process_instances.id'], name=op.f('fk_counterparties_created_from_process_id_process_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties')),
    sa.UniqueConstraint('external_id', name=op.f('uq_counterparties_external_id'))
    )
    op.create_index(op.f('ix_counterparties_bin'), 'counterparties', ['bin'], unique=False)
    op.create_table('tasks',
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('order_in_stage', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('substitute_for_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('result', sa.Enum('APPROVED', 'REJECTED', 'AUTO_APPROVED', name='taskresult'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['employees.id'], name=op.f('fk_tasks_assignee_id_employees')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_tasks_position_id_positions')),
    sa.ForeignKeyConstraint(['process_id'], ['process_instances.id'], name=op.f('fk_tasks_process_id_process_instances')),
    sa.ForeignKeyConstraint(['substitute_for_id'], ['employees.id'], name=op.f('fk_tasks_substitute_for_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_table('audit_log',
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_instances.id'], name=op.f('fk_audit_log_process_id_process_instances')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_audit_log_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('contracts',
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('responsible_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.UUID(), nullable=True),
    sa.Column('sync_status', sa.Enum('DRAFT', 'PENDING', 'SYNCED', 'FAILED', name='contractsyncstatus'), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_contracts_counterparty_id_counterparties')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contracts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['process_id'], ['process_instances.id'], name=op.f('fk_contracts_process_id_process_instances')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_contracts_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_id'], ['employees.id'], name=op.f('fk_contracts_responsible_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('external_id', name=op.f('uq_contracts_external_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    op.drop_table('audit_log')
    op.drop_index('ix_tasks_assignee_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_counterparties_bin'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index('ix_route_rules_context', table_name='route_rules')
    op.drop_table('route_rules')
    op.drop_table('project_assignments')
    op.drop_table('process_instances')
    op.drop_table('memos')
    op.drop_table('employments')
    op.drop_table('users')
    op.drop_table('substitutions')
    op.drop_table('projects')
    op.drop_table('departments')
    op.drop_table('absences')
    op.drop_table('sync_log')
    op.drop_table('positions')
    op.drop_table('organizations')
    op.drop_table('integration_outbox')
    op.drop_table('external_mapping')
    op.drop_table('employees')
    # ### end Alembic commands ###
