export const AUDIT_LABELS: Record<string, string> = {
  PROCESS_STARTED: 'Процесс запущен',
  TASK_APPROVED: 'Согласовано',
  TASK_REJECTED: 'Отклонено',
  TASK_AUTO_APPROVED: 'Автосогласовано',
  TASK_EXECUTED: 'Исполнено',
  TASK_NOT_EXECUTED: 'Не выполнено',
  TASK_ACKNOWLEDGED: 'Ознакомлен',
  TASK_RETURNED: 'Возвращено на доработку',
  PROCESS_RETURNED: 'Процесс возвращён на доработку',
  PROCESS_RESUBMITTED: 'Отправлен повторно после доработки',
  PROCESS_APPROVED: 'Процесс согласован',
  PROCESS_REJECTED: 'Процесс отклонён',
  PROCESS_CANCELLED: 'Процесс отозван инициатором',
  PROCESS_FORCE_CLOSED: 'Процесс закрыт администратором',
}
